#pragma checksum "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CADFD7EDB224AF78C79F0F83F1705207"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfCsSample.CodeSampleControls.BitmapAssistedSegmentation;


namespace WpfCsSample.CodeSampleControls.BitmapAssistedSegmentation {
    
    
    /// <summary>
    /// BitmapAssistedSegmentationControl
    /// </summary>
    public partial class BitmapAssistedSegmentationControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 59 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image OriginalImage;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas Shadow;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image SegmentedItemImage;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path SegmentedItemOutline;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.InkCanvas StrokeCanvas;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfCsSample;component/codesamplecontrols/bitmapassistedsegmentation/bitmapassist" +
                    "edsegmentationcontrol.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 18 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.LoadImageFromDisk_Clicked);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 42 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearStroke_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 47 "..\..\..\..\..\..\..\CodeSampleControls\BitmapAssistedSegmentation\BitmapAssistedSegmentationControl.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PerformAssistedSegmentation_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.OriginalImage = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.Shadow = ((System.Windows.Controls.Canvas)(target));
            return;
            case 6:
            this.SegmentedItemImage = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.SegmentedItemOutline = ((System.Windows.Shapes.Path)(target));
            return;
            case 8:
            this.StrokeCanvas = ((System.Windows.Controls.InkCanvas)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

